url: "https://kimera.world"

permalink: pretty
template_engine: liquid

timezone: Europe/London

pagination:
  enabled: true

collections:
  posts:
    output: true
    permalink: pretty
  projects:
    output: true
    permalink: simple
  resources:
    output: true
    permalink: simple

feed:
  collections:
    posts:
      path: "/posts/feed.xml"
    projects:
      path: "/projects/feed.xml"